<?php

namespace TextKernel\saveresults;

class errorCode
{
    const __default = 'EMPTY_ARGUMENT';
    const EMPTY_ARGUMENT = 'EMPTY_ARGUMENT';
    const INVALID_PASSWORD = 'INVALID_PASSWORD';
    const INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN';
    const INVALID_EXTERNAL_TOKEN = 'INVALID_EXTERNAL_TOKEN';
    const ENVIRONMENT_NOT_AVAILABLE = 'ENVIRONMENT_NOT_AVAILABLE';
    const DOCUMENT_FORMAT_ERROR = 'DOCUMENT_FORMAT_ERROR';
    const DOCUMENT_STORAGE_ERROR = 'DOCUMENT_STORAGE_ERROR';
    const INVALID_ACCESS_ROLES = 'INVALID_ACCESS_ROLES';
    const INVALID_SEARCH_REQUEST = 'INVALID_SEARCH_REQUEST';
    const SEARCH_EXECUTION_ERROR = 'SEARCH_EXECUTION_ERROR';
    const QUERY_EXTRACTION_CONFIGURATION_ERROR = 'QUERY_EXTRACTION_CONFIGURATION_ERROR';
    const URL_NOT_FOUND = 'URL_NOT_FOUND';
    const QUERY_EXTRACTION_EXECUTION_ERROR = 'QUERY_EXTRACTION_EXECUTION_ERROR';
    const EXTERNAL_LOGIN_ERROR = 'EXTERNAL_LOGIN_ERROR';
    const INVALID_ACTION = 'INVALID_ACTION';
    const DATABASE_ERROR = 'DATABASE_ERROR';
    const INVALID_SEARCH_STATE = 'INVALID_SEARCH_STATE';
    const SAVED_SEARCH_NOT_FOUND = 'SAVED_SEARCH_NOT_FOUND';
    const SAVED_RESULT_NOT_FOUND = 'SAVED_RESULT_NOT_FOUND';
    const PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND';
    const INVALID_EMAIL_ADDRESSES = 'INVALID_EMAIL_ADDRESSES';
    const NOT_ENOUGH_CHARACTERS = 'NOT_ENOUGH_CHARACTERS';
    const NO_DICTIONARY_FOR_FIELD = 'NO_DICTIONARY_FOR_FIELD';
    const PROJECT_ACCESS_DENIED = 'PROJECT_ACCESS_DENIED';
    const INVALID_SAVE_RESULTS_REQUEST = 'INVALID_SAVE_RESULTS_REQUEST';
    const INVALID_LOGGING_REQUEST = 'INVALID_LOGGING_REQUEST';
    const METHOD_NOT_AVAILABLE = 'METHOD_NOT_AVAILABLE';
    const PROJECT_DATA_NOT_UNIQUE = 'PROJECT_DATA_NOT_UNIQUE';
    const FILE_ACCESS_DENIED = 'FILE_ACCESS_DENIED';
    const SEARCHER_NOT_FOUND = 'SEARCHER_NOT_FOUND';
    const INVALID_KNOWLEDGE_FILE = 'INVALID_KNOWLEDGE_FILE';
    const SEARCHER_ACCESS_DENIED = 'SEARCHER_ACCESS_DENIED';
    const INVALID_DATE = 'INVALID_DATE';
    const EXTERNAL_ERROR = 'EXTERNAL_ERROR';
    const USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED';
    const SESSION_TIMEOUT = 'SESSION_TIMEOUT';


}
